# Generated by Django 5.1.4 on 2025-01-07 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stock_movement',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
